# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/son/Documents/OOB_PROJECT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/son/Documents/OOB_PROJECT/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/son/Documents/OOB_PROJECT/build/CMakeFiles /Users/son/Documents/OOB_PROJECT/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/son/Documents/OOB_PROJECT/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/son/Documents/OOB_PROJECT/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Hotel_Management

# Build rule for target.
Hotel_Management: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Hotel_Management
.PHONY : Hotel_Management

# fast build rule for target.
Hotel_Management/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/build
.PHONY : Hotel_Management/fast

#=============================================================================
# Target rules for targets named Hotel_Management_autogen_timestamp_deps

# Build rule for target.
Hotel_Management_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Hotel_Management_autogen_timestamp_deps
.PHONY : Hotel_Management_autogen_timestamp_deps

# fast build rule for target.
Hotel_Management_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_autogen_timestamp_deps.dir/build.make CMakeFiles/Hotel_Management_autogen_timestamp_deps.dir/build
.PHONY : Hotel_Management_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named Hotel_Management_autogen

# Build rule for target.
Hotel_Management_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Hotel_Management_autogen
.PHONY : Hotel_Management_autogen

# fast build rule for target.
Hotel_Management_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management_autogen.dir/build.make CMakeFiles/Hotel_Management_autogen.dir/build
.PHONY : Hotel_Management_autogen/fast

Hotel_Management_autogen/mocs_compilation.o: Hotel_Management_autogen/mocs_compilation.cpp.o
.PHONY : Hotel_Management_autogen/mocs_compilation.o

# target to build an object file
Hotel_Management_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/Hotel_Management_autogen/mocs_compilation.cpp.o
.PHONY : Hotel_Management_autogen/mocs_compilation.cpp.o

Hotel_Management_autogen/mocs_compilation.i: Hotel_Management_autogen/mocs_compilation.cpp.i
.PHONY : Hotel_Management_autogen/mocs_compilation.i

# target to preprocess a source file
Hotel_Management_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/Hotel_Management_autogen/mocs_compilation.cpp.i
.PHONY : Hotel_Management_autogen/mocs_compilation.cpp.i

Hotel_Management_autogen/mocs_compilation.s: Hotel_Management_autogen/mocs_compilation.cpp.s
.PHONY : Hotel_Management_autogen/mocs_compilation.s

# target to generate assembly for a file
Hotel_Management_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/Hotel_Management_autogen/mocs_compilation.cpp.s
.PHONY : Hotel_Management_autogen/mocs_compilation.cpp.s

backend/Manager/BillingService.o: backend/Manager/BillingService.cpp.o
.PHONY : backend/Manager/BillingService.o

# target to build an object file
backend/Manager/BillingService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Manager/BillingService.cpp.o
.PHONY : backend/Manager/BillingService.cpp.o

backend/Manager/BillingService.i: backend/Manager/BillingService.cpp.i
.PHONY : backend/Manager/BillingService.i

# target to preprocess a source file
backend/Manager/BillingService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Manager/BillingService.cpp.i
.PHONY : backend/Manager/BillingService.cpp.i

backend/Manager/BillingService.s: backend/Manager/BillingService.cpp.s
.PHONY : backend/Manager/BillingService.s

# target to generate assembly for a file
backend/Manager/BillingService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Manager/BillingService.cpp.s
.PHONY : backend/Manager/BillingService.cpp.s

backend/Manager/DashboardService.o: backend/Manager/DashboardService.cpp.o
.PHONY : backend/Manager/DashboardService.o

# target to build an object file
backend/Manager/DashboardService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Manager/DashboardService.cpp.o
.PHONY : backend/Manager/DashboardService.cpp.o

backend/Manager/DashboardService.i: backend/Manager/DashboardService.cpp.i
.PHONY : backend/Manager/DashboardService.i

# target to preprocess a source file
backend/Manager/DashboardService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Manager/DashboardService.cpp.i
.PHONY : backend/Manager/DashboardService.cpp.i

backend/Manager/DashboardService.s: backend/Manager/DashboardService.cpp.s
.PHONY : backend/Manager/DashboardService.s

# target to generate assembly for a file
backend/Manager/DashboardService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Manager/DashboardService.cpp.s
.PHONY : backend/Manager/DashboardService.cpp.s

backend/Manager/DatabaseManager.o: backend/Manager/DatabaseManager.cpp.o
.PHONY : backend/Manager/DatabaseManager.o

# target to build an object file
backend/Manager/DatabaseManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Manager/DatabaseManager.cpp.o
.PHONY : backend/Manager/DatabaseManager.cpp.o

backend/Manager/DatabaseManager.i: backend/Manager/DatabaseManager.cpp.i
.PHONY : backend/Manager/DatabaseManager.i

# target to preprocess a source file
backend/Manager/DatabaseManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Manager/DatabaseManager.cpp.i
.PHONY : backend/Manager/DatabaseManager.cpp.i

backend/Manager/DatabaseManager.s: backend/Manager/DatabaseManager.cpp.s
.PHONY : backend/Manager/DatabaseManager.s

# target to generate assembly for a file
backend/Manager/DatabaseManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Manager/DatabaseManager.cpp.s
.PHONY : backend/Manager/DatabaseManager.cpp.s

backend/Repository/BookingRepository.o: backend/Repository/BookingRepository.cpp.o
.PHONY : backend/Repository/BookingRepository.o

# target to build an object file
backend/Repository/BookingRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/BookingRepository.cpp.o
.PHONY : backend/Repository/BookingRepository.cpp.o

backend/Repository/BookingRepository.i: backend/Repository/BookingRepository.cpp.i
.PHONY : backend/Repository/BookingRepository.i

# target to preprocess a source file
backend/Repository/BookingRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/BookingRepository.cpp.i
.PHONY : backend/Repository/BookingRepository.cpp.i

backend/Repository/BookingRepository.s: backend/Repository/BookingRepository.cpp.s
.PHONY : backend/Repository/BookingRepository.s

# target to generate assembly for a file
backend/Repository/BookingRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/BookingRepository.cpp.s
.PHONY : backend/Repository/BookingRepository.cpp.s

backend/Repository/CustomerRepository.o: backend/Repository/CustomerRepository.cpp.o
.PHONY : backend/Repository/CustomerRepository.o

# target to build an object file
backend/Repository/CustomerRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/CustomerRepository.cpp.o
.PHONY : backend/Repository/CustomerRepository.cpp.o

backend/Repository/CustomerRepository.i: backend/Repository/CustomerRepository.cpp.i
.PHONY : backend/Repository/CustomerRepository.i

# target to preprocess a source file
backend/Repository/CustomerRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/CustomerRepository.cpp.i
.PHONY : backend/Repository/CustomerRepository.cpp.i

backend/Repository/CustomerRepository.s: backend/Repository/CustomerRepository.cpp.s
.PHONY : backend/Repository/CustomerRepository.s

# target to generate assembly for a file
backend/Repository/CustomerRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/CustomerRepository.cpp.s
.PHONY : backend/Repository/CustomerRepository.cpp.s

backend/Repository/FoodRepository.o: backend/Repository/FoodRepository.cpp.o
.PHONY : backend/Repository/FoodRepository.o

# target to build an object file
backend/Repository/FoodRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/FoodRepository.cpp.o
.PHONY : backend/Repository/FoodRepository.cpp.o

backend/Repository/FoodRepository.i: backend/Repository/FoodRepository.cpp.i
.PHONY : backend/Repository/FoodRepository.i

# target to preprocess a source file
backend/Repository/FoodRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/FoodRepository.cpp.i
.PHONY : backend/Repository/FoodRepository.cpp.i

backend/Repository/FoodRepository.s: backend/Repository/FoodRepository.cpp.s
.PHONY : backend/Repository/FoodRepository.s

# target to generate assembly for a file
backend/Repository/FoodRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/FoodRepository.cpp.s
.PHONY : backend/Repository/FoodRepository.cpp.s

backend/Repository/InventoryRepository.o: backend/Repository/InventoryRepository.cpp.o
.PHONY : backend/Repository/InventoryRepository.o

# target to build an object file
backend/Repository/InventoryRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/InventoryRepository.cpp.o
.PHONY : backend/Repository/InventoryRepository.cpp.o

backend/Repository/InventoryRepository.i: backend/Repository/InventoryRepository.cpp.i
.PHONY : backend/Repository/InventoryRepository.i

# target to preprocess a source file
backend/Repository/InventoryRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/InventoryRepository.cpp.i
.PHONY : backend/Repository/InventoryRepository.cpp.i

backend/Repository/InventoryRepository.s: backend/Repository/InventoryRepository.cpp.s
.PHONY : backend/Repository/InventoryRepository.s

# target to generate assembly for a file
backend/Repository/InventoryRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/InventoryRepository.cpp.s
.PHONY : backend/Repository/InventoryRepository.cpp.s

backend/Repository/InvoiceRepository.o: backend/Repository/InvoiceRepository.cpp.o
.PHONY : backend/Repository/InvoiceRepository.o

# target to build an object file
backend/Repository/InvoiceRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/InvoiceRepository.cpp.o
.PHONY : backend/Repository/InvoiceRepository.cpp.o

backend/Repository/InvoiceRepository.i: backend/Repository/InvoiceRepository.cpp.i
.PHONY : backend/Repository/InvoiceRepository.i

# target to preprocess a source file
backend/Repository/InvoiceRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/InvoiceRepository.cpp.i
.PHONY : backend/Repository/InvoiceRepository.cpp.i

backend/Repository/InvoiceRepository.s: backend/Repository/InvoiceRepository.cpp.s
.PHONY : backend/Repository/InvoiceRepository.s

# target to generate assembly for a file
backend/Repository/InvoiceRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/InvoiceRepository.cpp.s
.PHONY : backend/Repository/InvoiceRepository.cpp.s

backend/Repository/RoomRepository.o: backend/Repository/RoomRepository.cpp.o
.PHONY : backend/Repository/RoomRepository.o

# target to build an object file
backend/Repository/RoomRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/RoomRepository.cpp.o
.PHONY : backend/Repository/RoomRepository.cpp.o

backend/Repository/RoomRepository.i: backend/Repository/RoomRepository.cpp.i
.PHONY : backend/Repository/RoomRepository.i

# target to preprocess a source file
backend/Repository/RoomRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/RoomRepository.cpp.i
.PHONY : backend/Repository/RoomRepository.cpp.i

backend/Repository/RoomRepository.s: backend/Repository/RoomRepository.cpp.s
.PHONY : backend/Repository/RoomRepository.s

# target to generate assembly for a file
backend/Repository/RoomRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/RoomRepository.cpp.s
.PHONY : backend/Repository/RoomRepository.cpp.s

backend/Repository/ServiceItemRepository.o: backend/Repository/ServiceItemRepository.cpp.o
.PHONY : backend/Repository/ServiceItemRepository.o

# target to build an object file
backend/Repository/ServiceItemRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/ServiceItemRepository.cpp.o
.PHONY : backend/Repository/ServiceItemRepository.cpp.o

backend/Repository/ServiceItemRepository.i: backend/Repository/ServiceItemRepository.cpp.i
.PHONY : backend/Repository/ServiceItemRepository.i

# target to preprocess a source file
backend/Repository/ServiceItemRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/ServiceItemRepository.cpp.i
.PHONY : backend/Repository/ServiceItemRepository.cpp.i

backend/Repository/ServiceItemRepository.s: backend/Repository/ServiceItemRepository.cpp.s
.PHONY : backend/Repository/ServiceItemRepository.s

# target to generate assembly for a file
backend/Repository/ServiceItemRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/backend/Repository/ServiceItemRepository.cpp.s
.PHONY : backend/Repository/ServiceItemRepository.cpp.s

cores/Booking/Booking.o: cores/Booking/Booking.cpp.o
.PHONY : cores/Booking/Booking.o

# target to build an object file
cores/Booking/Booking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Booking/Booking.cpp.o
.PHONY : cores/Booking/Booking.cpp.o

cores/Booking/Booking.i: cores/Booking/Booking.cpp.i
.PHONY : cores/Booking/Booking.i

# target to preprocess a source file
cores/Booking/Booking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Booking/Booking.cpp.i
.PHONY : cores/Booking/Booking.cpp.i

cores/Booking/Booking.s: cores/Booking/Booking.cpp.s
.PHONY : cores/Booking/Booking.s

# target to generate assembly for a file
cores/Booking/Booking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Booking/Booking.cpp.s
.PHONY : cores/Booking/Booking.cpp.s

cores/Booking/BookingFactory.o: cores/Booking/BookingFactory.cpp.o
.PHONY : cores/Booking/BookingFactory.o

# target to build an object file
cores/Booking/BookingFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Booking/BookingFactory.cpp.o
.PHONY : cores/Booking/BookingFactory.cpp.o

cores/Booking/BookingFactory.i: cores/Booking/BookingFactory.cpp.i
.PHONY : cores/Booking/BookingFactory.i

# target to preprocess a source file
cores/Booking/BookingFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Booking/BookingFactory.cpp.i
.PHONY : cores/Booking/BookingFactory.cpp.i

cores/Booking/BookingFactory.s: cores/Booking/BookingFactory.cpp.s
.PHONY : cores/Booking/BookingFactory.s

# target to generate assembly for a file
cores/Booking/BookingFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Booking/BookingFactory.cpp.s
.PHONY : cores/Booking/BookingFactory.cpp.s

cores/Customer/Customer.o: cores/Customer/Customer.cpp.o
.PHONY : cores/Customer/Customer.o

# target to build an object file
cores/Customer/Customer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Customer/Customer.cpp.o
.PHONY : cores/Customer/Customer.cpp.o

cores/Customer/Customer.i: cores/Customer/Customer.cpp.i
.PHONY : cores/Customer/Customer.i

# target to preprocess a source file
cores/Customer/Customer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Customer/Customer.cpp.i
.PHONY : cores/Customer/Customer.cpp.i

cores/Customer/Customer.s: cores/Customer/Customer.cpp.s
.PHONY : cores/Customer/Customer.s

# target to generate assembly for a file
cores/Customer/Customer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Customer/Customer.cpp.s
.PHONY : cores/Customer/Customer.cpp.s

cores/Customer/MembershipPolicy.o: cores/Customer/MembershipPolicy.cpp.o
.PHONY : cores/Customer/MembershipPolicy.o

# target to build an object file
cores/Customer/MembershipPolicy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Customer/MembershipPolicy.cpp.o
.PHONY : cores/Customer/MembershipPolicy.cpp.o

cores/Customer/MembershipPolicy.i: cores/Customer/MembershipPolicy.cpp.i
.PHONY : cores/Customer/MembershipPolicy.i

# target to preprocess a source file
cores/Customer/MembershipPolicy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Customer/MembershipPolicy.cpp.i
.PHONY : cores/Customer/MembershipPolicy.cpp.i

cores/Customer/MembershipPolicy.s: cores/Customer/MembershipPolicy.cpp.s
.PHONY : cores/Customer/MembershipPolicy.s

# target to generate assembly for a file
cores/Customer/MembershipPolicy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Customer/MembershipPolicy.cpp.s
.PHONY : cores/Customer/MembershipPolicy.cpp.s

cores/Room/DerivedRooms.o: cores/Room/DerivedRooms.cpp.o
.PHONY : cores/Room/DerivedRooms.o

# target to build an object file
cores/Room/DerivedRooms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Room/DerivedRooms.cpp.o
.PHONY : cores/Room/DerivedRooms.cpp.o

cores/Room/DerivedRooms.i: cores/Room/DerivedRooms.cpp.i
.PHONY : cores/Room/DerivedRooms.i

# target to preprocess a source file
cores/Room/DerivedRooms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Room/DerivedRooms.cpp.i
.PHONY : cores/Room/DerivedRooms.cpp.i

cores/Room/DerivedRooms.s: cores/Room/DerivedRooms.cpp.s
.PHONY : cores/Room/DerivedRooms.s

# target to generate assembly for a file
cores/Room/DerivedRooms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Room/DerivedRooms.cpp.s
.PHONY : cores/Room/DerivedRooms.cpp.s

cores/Room/Room.o: cores/Room/Room.cpp.o
.PHONY : cores/Room/Room.o

# target to build an object file
cores/Room/Room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Room/Room.cpp.o
.PHONY : cores/Room/Room.cpp.o

cores/Room/Room.i: cores/Room/Room.cpp.i
.PHONY : cores/Room/Room.i

# target to preprocess a source file
cores/Room/Room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Room/Room.cpp.i
.PHONY : cores/Room/Room.cpp.i

cores/Room/Room.s: cores/Room/Room.cpp.s
.PHONY : cores/Room/Room.s

# target to generate assembly for a file
cores/Room/Room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Room/Room.cpp.s
.PHONY : cores/Room/Room.cpp.s

cores/Room/RoomFactory.o: cores/Room/RoomFactory.cpp.o
.PHONY : cores/Room/RoomFactory.o

# target to build an object file
cores/Room/RoomFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Room/RoomFactory.cpp.o
.PHONY : cores/Room/RoomFactory.cpp.o

cores/Room/RoomFactory.i: cores/Room/RoomFactory.cpp.i
.PHONY : cores/Room/RoomFactory.i

# target to preprocess a source file
cores/Room/RoomFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Room/RoomFactory.cpp.i
.PHONY : cores/Room/RoomFactory.cpp.i

cores/Room/RoomFactory.s: cores/Room/RoomFactory.cpp.s
.PHONY : cores/Room/RoomFactory.s

# target to generate assembly for a file
cores/Room/RoomFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Room/RoomFactory.cpp.s
.PHONY : cores/Room/RoomFactory.cpp.s

cores/Service/InventoryService.o: cores/Service/InventoryService.cpp.o
.PHONY : cores/Service/InventoryService.o

# target to build an object file
cores/Service/InventoryService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Service/InventoryService.cpp.o
.PHONY : cores/Service/InventoryService.cpp.o

cores/Service/InventoryService.i: cores/Service/InventoryService.cpp.i
.PHONY : cores/Service/InventoryService.i

# target to preprocess a source file
cores/Service/InventoryService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Service/InventoryService.cpp.i
.PHONY : cores/Service/InventoryService.cpp.i

cores/Service/InventoryService.s: cores/Service/InventoryService.cpp.s
.PHONY : cores/Service/InventoryService.s

# target to generate assembly for a file
cores/Service/InventoryService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Service/InventoryService.cpp.s
.PHONY : cores/Service/InventoryService.cpp.s

cores/Service/ServiceItem.o: cores/Service/ServiceItem.cpp.o
.PHONY : cores/Service/ServiceItem.o

# target to build an object file
cores/Service/ServiceItem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Service/ServiceItem.cpp.o
.PHONY : cores/Service/ServiceItem.cpp.o

cores/Service/ServiceItem.i: cores/Service/ServiceItem.cpp.i
.PHONY : cores/Service/ServiceItem.i

# target to preprocess a source file
cores/Service/ServiceItem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Service/ServiceItem.cpp.i
.PHONY : cores/Service/ServiceItem.cpp.i

cores/Service/ServiceItem.s: cores/Service/ServiceItem.cpp.s
.PHONY : cores/Service/ServiceItem.s

# target to generate assembly for a file
cores/Service/ServiceItem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/cores/Service/ServiceItem.cpp.s
.PHONY : cores/Service/ServiceItem.cpp.s

frontend/Checkout/Checkoutpage.o: frontend/Checkout/Checkoutpage.cpp.o
.PHONY : frontend/Checkout/Checkoutpage.o

# target to build an object file
frontend/Checkout/Checkoutpage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/Checkout/Checkoutpage.cpp.o
.PHONY : frontend/Checkout/Checkoutpage.cpp.o

frontend/Checkout/Checkoutpage.i: frontend/Checkout/Checkoutpage.cpp.i
.PHONY : frontend/Checkout/Checkoutpage.i

# target to preprocess a source file
frontend/Checkout/Checkoutpage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/Checkout/Checkoutpage.cpp.i
.PHONY : frontend/Checkout/Checkoutpage.cpp.i

frontend/Checkout/Checkoutpage.s: frontend/Checkout/Checkoutpage.cpp.s
.PHONY : frontend/Checkout/Checkoutpage.s

# target to generate assembly for a file
frontend/Checkout/Checkoutpage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/Checkout/Checkoutpage.cpp.s
.PHONY : frontend/Checkout/Checkoutpage.cpp.s

frontend/Observers/Observer.o: frontend/Observers/Observer.cpp.o
.PHONY : frontend/Observers/Observer.o

# target to build an object file
frontend/Observers/Observer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/Observers/Observer.cpp.o
.PHONY : frontend/Observers/Observer.cpp.o

frontend/Observers/Observer.i: frontend/Observers/Observer.cpp.i
.PHONY : frontend/Observers/Observer.i

# target to preprocess a source file
frontend/Observers/Observer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/Observers/Observer.cpp.i
.PHONY : frontend/Observers/Observer.cpp.i

frontend/Observers/Observer.s: frontend/Observers/Observer.cpp.s
.PHONY : frontend/Observers/Observer.s

# target to generate assembly for a file
frontend/Observers/Observer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/Observers/Observer.cpp.s
.PHONY : frontend/Observers/Observer.cpp.s

frontend/Observers/QtHotelObserver.o: frontend/Observers/QtHotelObserver.cpp.o
.PHONY : frontend/Observers/QtHotelObserver.o

# target to build an object file
frontend/Observers/QtHotelObserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/Observers/QtHotelObserver.cpp.o
.PHONY : frontend/Observers/QtHotelObserver.cpp.o

frontend/Observers/QtHotelObserver.i: frontend/Observers/QtHotelObserver.cpp.i
.PHONY : frontend/Observers/QtHotelObserver.i

# target to preprocess a source file
frontend/Observers/QtHotelObserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/Observers/QtHotelObserver.cpp.i
.PHONY : frontend/Observers/QtHotelObserver.cpp.i

frontend/Observers/QtHotelObserver.s: frontend/Observers/QtHotelObserver.cpp.s
.PHONY : frontend/Observers/QtHotelObserver.s

# target to generate assembly for a file
frontend/Observers/QtHotelObserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/Observers/QtHotelObserver.cpp.s
.PHONY : frontend/Observers/QtHotelObserver.cpp.s

frontend/UI/CustomerWindow/Customerwin.o: frontend/UI/CustomerWindow/Customerwin.cpp.o
.PHONY : frontend/UI/CustomerWindow/Customerwin.o

# target to build an object file
frontend/UI/CustomerWindow/Customerwin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UI/CustomerWindow/Customerwin.cpp.o
.PHONY : frontend/UI/CustomerWindow/Customerwin.cpp.o

frontend/UI/CustomerWindow/Customerwin.i: frontend/UI/CustomerWindow/Customerwin.cpp.i
.PHONY : frontend/UI/CustomerWindow/Customerwin.i

# target to preprocess a source file
frontend/UI/CustomerWindow/Customerwin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UI/CustomerWindow/Customerwin.cpp.i
.PHONY : frontend/UI/CustomerWindow/Customerwin.cpp.i

frontend/UI/CustomerWindow/Customerwin.s: frontend/UI/CustomerWindow/Customerwin.cpp.s
.PHONY : frontend/UI/CustomerWindow/Customerwin.s

# target to generate assembly for a file
frontend/UI/CustomerWindow/Customerwin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UI/CustomerWindow/Customerwin.cpp.s
.PHONY : frontend/UI/CustomerWindow/Customerwin.cpp.s

frontend/UI/Login/Login.o: frontend/UI/Login/Login.cpp.o
.PHONY : frontend/UI/Login/Login.o

# target to build an object file
frontend/UI/Login/Login.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UI/Login/Login.cpp.o
.PHONY : frontend/UI/Login/Login.cpp.o

frontend/UI/Login/Login.i: frontend/UI/Login/Login.cpp.i
.PHONY : frontend/UI/Login/Login.i

# target to preprocess a source file
frontend/UI/Login/Login.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UI/Login/Login.cpp.i
.PHONY : frontend/UI/Login/Login.cpp.i

frontend/UI/Login/Login.s: frontend/UI/Login/Login.cpp.s
.PHONY : frontend/UI/Login/Login.s

# target to generate assembly for a file
frontend/UI/Login/Login.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UI/Login/Login.cpp.s
.PHONY : frontend/UI/Login/Login.cpp.s

frontend/UI/UI.o: frontend/UI/UI.cpp.o
.PHONY : frontend/UI/UI.o

# target to build an object file
frontend/UI/UI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UI/UI.cpp.o
.PHONY : frontend/UI/UI.cpp.o

frontend/UI/UI.i: frontend/UI/UI.cpp.i
.PHONY : frontend/UI/UI.i

# target to preprocess a source file
frontend/UI/UI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UI/UI.cpp.i
.PHONY : frontend/UI/UI.cpp.i

frontend/UI/UI.s: frontend/UI/UI.cpp.s
.PHONY : frontend/UI/UI.s

# target to generate assembly for a file
frontend/UI/UI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UI/UI.cpp.s
.PHONY : frontend/UI/UI.cpp.s

frontend/UX/UX.o: frontend/UX/UX.cpp.o
.PHONY : frontend/UX/UX.o

# target to build an object file
frontend/UX/UX.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UX/UX.cpp.o
.PHONY : frontend/UX/UX.cpp.o

frontend/UX/UX.i: frontend/UX/UX.cpp.i
.PHONY : frontend/UX/UX.i

# target to preprocess a source file
frontend/UX/UX.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UX/UX.cpp.i
.PHONY : frontend/UX/UX.cpp.i

frontend/UX/UX.s: frontend/UX/UX.cpp.s
.PHONY : frontend/UX/UX.s

# target to generate assembly for a file
frontend/UX/UX.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/UX/UX.cpp.s
.PHONY : frontend/UX/UX.cpp.s

frontend/usercheck/backend.o: frontend/usercheck/backend.cpp.o
.PHONY : frontend/usercheck/backend.o

# target to build an object file
frontend/usercheck/backend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/usercheck/backend.cpp.o
.PHONY : frontend/usercheck/backend.cpp.o

frontend/usercheck/backend.i: frontend/usercheck/backend.cpp.i
.PHONY : frontend/usercheck/backend.i

# target to preprocess a source file
frontend/usercheck/backend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/usercheck/backend.cpp.i
.PHONY : frontend/usercheck/backend.cpp.i

frontend/usercheck/backend.s: frontend/usercheck/backend.cpp.s
.PHONY : frontend/usercheck/backend.s

# target to generate assembly for a file
frontend/usercheck/backend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/frontend/usercheck/backend.cpp.s
.PHONY : frontend/usercheck/backend.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hotel_Management.dir/build.make CMakeFiles/Hotel_Management.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Hotel_Management_autogen"
	@echo "... Hotel_Management_autogen_timestamp_deps"
	@echo "... Hotel_Management"
	@echo "... Hotel_Management_autogen/mocs_compilation.o"
	@echo "... Hotel_Management_autogen/mocs_compilation.i"
	@echo "... Hotel_Management_autogen/mocs_compilation.s"
	@echo "... backend/Manager/BillingService.o"
	@echo "... backend/Manager/BillingService.i"
	@echo "... backend/Manager/BillingService.s"
	@echo "... backend/Manager/DashboardService.o"
	@echo "... backend/Manager/DashboardService.i"
	@echo "... backend/Manager/DashboardService.s"
	@echo "... backend/Manager/DatabaseManager.o"
	@echo "... backend/Manager/DatabaseManager.i"
	@echo "... backend/Manager/DatabaseManager.s"
	@echo "... backend/Repository/BookingRepository.o"
	@echo "... backend/Repository/BookingRepository.i"
	@echo "... backend/Repository/BookingRepository.s"
	@echo "... backend/Repository/CustomerRepository.o"
	@echo "... backend/Repository/CustomerRepository.i"
	@echo "... backend/Repository/CustomerRepository.s"
	@echo "... backend/Repository/FoodRepository.o"
	@echo "... backend/Repository/FoodRepository.i"
	@echo "... backend/Repository/FoodRepository.s"
	@echo "... backend/Repository/InventoryRepository.o"
	@echo "... backend/Repository/InventoryRepository.i"
	@echo "... backend/Repository/InventoryRepository.s"
	@echo "... backend/Repository/InvoiceRepository.o"
	@echo "... backend/Repository/InvoiceRepository.i"
	@echo "... backend/Repository/InvoiceRepository.s"
	@echo "... backend/Repository/RoomRepository.o"
	@echo "... backend/Repository/RoomRepository.i"
	@echo "... backend/Repository/RoomRepository.s"
	@echo "... backend/Repository/ServiceItemRepository.o"
	@echo "... backend/Repository/ServiceItemRepository.i"
	@echo "... backend/Repository/ServiceItemRepository.s"
	@echo "... cores/Booking/Booking.o"
	@echo "... cores/Booking/Booking.i"
	@echo "... cores/Booking/Booking.s"
	@echo "... cores/Booking/BookingFactory.o"
	@echo "... cores/Booking/BookingFactory.i"
	@echo "... cores/Booking/BookingFactory.s"
	@echo "... cores/Customer/Customer.o"
	@echo "... cores/Customer/Customer.i"
	@echo "... cores/Customer/Customer.s"
	@echo "... cores/Customer/MembershipPolicy.o"
	@echo "... cores/Customer/MembershipPolicy.i"
	@echo "... cores/Customer/MembershipPolicy.s"
	@echo "... cores/Room/DerivedRooms.o"
	@echo "... cores/Room/DerivedRooms.i"
	@echo "... cores/Room/DerivedRooms.s"
	@echo "... cores/Room/Room.o"
	@echo "... cores/Room/Room.i"
	@echo "... cores/Room/Room.s"
	@echo "... cores/Room/RoomFactory.o"
	@echo "... cores/Room/RoomFactory.i"
	@echo "... cores/Room/RoomFactory.s"
	@echo "... cores/Service/InventoryService.o"
	@echo "... cores/Service/InventoryService.i"
	@echo "... cores/Service/InventoryService.s"
	@echo "... cores/Service/ServiceItem.o"
	@echo "... cores/Service/ServiceItem.i"
	@echo "... cores/Service/ServiceItem.s"
	@echo "... frontend/Checkout/Checkoutpage.o"
	@echo "... frontend/Checkout/Checkoutpage.i"
	@echo "... frontend/Checkout/Checkoutpage.s"
	@echo "... frontend/Observers/Observer.o"
	@echo "... frontend/Observers/Observer.i"
	@echo "... frontend/Observers/Observer.s"
	@echo "... frontend/Observers/QtHotelObserver.o"
	@echo "... frontend/Observers/QtHotelObserver.i"
	@echo "... frontend/Observers/QtHotelObserver.s"
	@echo "... frontend/UI/CustomerWindow/Customerwin.o"
	@echo "... frontend/UI/CustomerWindow/Customerwin.i"
	@echo "... frontend/UI/CustomerWindow/Customerwin.s"
	@echo "... frontend/UI/Login/Login.o"
	@echo "... frontend/UI/Login/Login.i"
	@echo "... frontend/UI/Login/Login.s"
	@echo "... frontend/UI/UI.o"
	@echo "... frontend/UI/UI.i"
	@echo "... frontend/UI/UI.s"
	@echo "... frontend/UX/UX.o"
	@echo "... frontend/UX/UX.i"
	@echo "... frontend/UX/UX.s"
	@echo "... frontend/usercheck/backend.o"
	@echo "... frontend/usercheck/backend.i"
	@echo "... frontend/usercheck/backend.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/son/Documents/OOB_PROJECT/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

